services:
  - type: web
    name: flask-docker-app
    env: docker
    buildCommand: docker build -t flask-docker-app .
    startCommand: python app.py
    dockerfilePath: ./Dockerfile
    port: 5000

