services:
  - type: web
    name: flask-devops-demo
    env: docker
    repo: https://github.com/rmicieli/flask-devops-demo
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - app.py
        - requirements.txt

